version: '3.4'

services:

  rabbitmq:
    container_name: 'rabbit'
    image: 'rabbitmq:3.11.15-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=pass'
    ports:
      - '5672:5672'
      - '15672:15672'
    
  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:3.4.0'
    hostname: 'localhost'
    volumes:
      - 'kafkavolume:/bitnami/kafka'
    ports:
      - '9092:9092'
    environment:
      - 'KAFKA_ENABLE_KRAFT=yes'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
  
  localstack:
    container_name: 'localstack'
    image: 'localstack/localstack:2.0'
    ports:
      - '4566:4566'            
      - '4510-4559:4510-4559'  
    environment:
      - 'DEBUG=1'
    volumes:
      - 'D:/Applications/CAP/localstack:/var/lib/localstack'

  nats:
    container_name: 'nats'
    image: 'nats:2.9-alpine'
    command:
      - '--js'
    ports:
      - '4222:4222'
      - '8222:8222'
      - '6222:6222'
    networks:
      - 'natsnetwork'
    volumes:
      - 'D:/Applications/CAP/nats:/tmp/nats/jetstream'
    
volumes:
  kafkavolume:
  zookeepervolume:
    
networks:
  natsnetwork:
