version: '3.4'

services:

  rabbitmq:
    image: 'rabbitmq:3.11.15-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - '5672:5672'
      - '15672:15672'